filmomania2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('filmovi/', include('filmovi.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

filmovi/urls.py
from django.urls import path
from .views import filmovi_lista

app_name = 'filmovi'

urlpatterns = [
    path('', filmovi_lista, name='filmovi_lista'),
]

home/urls.py
from django.urls import path
from .views import home


urlpatterns = [
    path('', home, name='home')
]

filmovi/models.py
from django.db import models

# Create your models here.
class Filmovi(models.Model):

    naslov = models.CharField(max_length=120)
    sadrzaj = models.TextField()

home/models.py
from django.db import models

# Create your models here.

filmovi/views.py
from django.shortcuts import render
from .models import Filmovi


# Create your views here.
def filmovi_lista(request):

    queryset = Filmovi.objects.all()

    context = {
        'queryset': queryset
    }
    return render(request, 'filmovi.html', context)

home/views.py
from django.shortcuts import render


# Create your views here.
def home(request):

    context = {

    }
    return render(request, 'home.html', context)

filmovi/templates/filmovi.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
  <link rel="stylesheet" href="{% static 'css/lista.css' %}">
{% endblock %}

{% block content %}
    <h1 class="naslov">Filmovi</h1>

    <div class="list-group lista">

    {% for qs in queryset %}
      <a href="#" class="list-group-item list-group-item-action">{{ qs.naslov }}</a>
    {% endfor %}

    </div>
{% endblock %}

home/templates/home.html
{% extends 'base.html' %}


{% block content %}
    <h1>Zdravo svete!</h1>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FilmoManiA #2</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    {% block css %} {% endblock %}
  </head>
  <body>

    {% include 'navbar.html' %}

    <div class="container-sm">

        <div class="unutr-kont">
            {% block content %}
            {% endblock %}
        </div>

    </div>

  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-sm bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Django-Vercel</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Pocetna</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'filmovi:filmovi_lista' %}">Filmovi</a>
        </li>
        
      </ul>
        <ul class="navbar-nav   mb-2 mb-lg-0">
            
        <li class="nav-item">
          <a class="nav-link" href="{% url 'filmovi:filmovi_lista' %}">Filmovi</a>
        </li>
        </ul>
      
    </div>
  </div>
</nav>